  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-info">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
              </div>
              <div class="card-body">
                <div class="form-group">
                  <label>Clave Actual</label>
                  <?php echo Form::password("a.clave1","maxlength='40' class='form-control' placeholder='Ingrese la Contraseña Actual'")?>
                </div>
                <div class="form-group">
                  <label>Nueva Clave</label>
                  <?php echo Form::password("a.clave2","maxlength='40' class='form-control' placeholder='Ingrese la Nueva Contraseña '")?>
                </div>
                <div class="form-group">
                  <label>Repita Clave</label>
                  <?php echo Form::password("a.clave3","maxlength='40' class='form-control' placeholder='Repita la Nueva Contraseña '")?>
                </div>
                <!-- /.form group -->

              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                  <button type="submit" class="btn btn-info float-right">Registrar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
