 <li class="nav-header">SUPER SAYA YIN</li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../rubro" class="nav-link">
              <i class="text-info fas fa-file nav-icon"></i>
              <p>Rubros</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../modulo" class="nav-link">
              <i class="text-warning fas fa-chart-pie nav-icon"></i>
              <p>Módulos</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../negocio" class="nav-link">
              <i class="text-success fas fa-tree nav-icon"></i>
              <p>Negocios</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../contrata" class="nav-link">
              <i class="text-info fas fa-table nav-icon"></i>
              <p>Contrataciones</p>
            </a>
          </li>
          
          <li class="nav-header">CONFIGURACION</li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../provincia" class="nav-link">
              <i class="text-warning fas fa-copy nav-icon"></i>
              <p>Provincias</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../localidad" class="nav-link">
              <i class="text-success fas fa-th nav-icon"></i>
              <p>Localidades</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../controlador" class="nav-link">
              <i class="text-info fas fa-book nav-icon"></i>
              <p>Controladores</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../accion" class="nav-link">
              <i class="text-danger fas fa-tachometer-alt nav-icon"></i>
              <p>Acciones de Acceso</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../rol" class="nav-link">
              <i class="text-warning far fa-user nav-icon"></i>
              <p>Roles</p>
            </a>
          </li>