  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#../../index3.html" class="brand-link">
      <img src="<?php echo PUBLIC_PATH?>AdminLTE-3.0.4/dist/img/AdminLTELogo.png"
           alt="AdminLTE Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">HipaTia 1ra</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="<?php echo AppController::$ANONIMO_FOTO?>" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="<?php echo AppController::$LINK_MISDATOS?>" class="d-block"><?php echo AppController::$ANONIMO_NOMBRE?></a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <?php if(Auth::get("rol_id")=="3") { 
                View::partial("clienteneg/left");
           ?>
          <?php } ?>
          <?php if(Auth::get("rol_id")=="2") { 
                View::partial("localadmin/left");
           ?>
          <?php } ?>
          <?php if(Auth::get("rol_id")=="1") { 
                View::partial("sayayin/left");
              ?>
         

          <?php }?>
          <li class="nav-header">MIS DATOS</li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH."../../usuario/clave/"?>" class="nav-link">
              <i class="nav-icon far fa-circle text-info"></i>
              <p>Cambiar Clave</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH."../../usuario/foto/"?>" class="nav-link">
              <i class="nav-icon far fa-circle text-info"></i>
              <p>Cambiar Foto</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>../../usuario/salir" class="nav-link">
              <i class="nav-icon far fa-circle text-warning"></i>
              <p>Salir Del Sistema</p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

