<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
          <h4>
        <a class="nav-link" data-widget="pushmenu" href="#" role="button">
            <i class="fas fa-bars"></i>
            <strong class="text-info"><?php echo $tit;?></strong>
        </a>
          </h4>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
        <!-- Messages Dropdown Menu -->
      <li class="nav-item ">
        <a class="nav-link btn btn-outline-primary " href="<?php echo PUBLIC_PATH?>../../usuario/salir">
            <span> <strong>Salir</strong></span>
<!--            <img src="<?php echo PUBLIC_PATH?>AdminLTE-3.0.4/dist/img/user1-128x128.jpg" 
                 alt="User Avatar" class="img-size-50 mr-3 img-circle" style="margin-top: -10px;">          -->
        </a>
      </li>
      
    </ul>
  </nav>
  <!-- /.navbar -->
