  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-info">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
                <a href="<?php echo $linkVolver;?>" class="btn btn-primary float-right">Volver</a>
              </div>
              <div class="card-body">
                  <?php Echo Form::hidden("a.id");?>
                <div class="form-group">
                  <label>Unidad</label>
                  <?php echo Form::text("a.unidad","maxlength='25' class='form-control' placeholder='Ingrese la unidad'")?>
                </div>
                <div class="form-group">
                  <label>Abreviatura</label>
                  <?php echo Form::text("a.abreviatura","maxlength='6' class='form-control' placeholder='Ingrese su Abreviatura'")?>
                </div>
                <!-- /.form group -->

                <!-- time Picker -->
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                  <button type="submit" class="btn btn-info float-right">Registrar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
