  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-info">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
                <a href="<?php echo $linkVolver;?>" class="btn btn-primary float-right">Volver</a>
              </div>
              <div class="card-body">
                <?php echo Form::hidden("a.id")?>
                <div class="form-group">
                  <label>Nombre de la Localidad</label>
                  <?php echo Form::text("a.loc","maxlength='30' class='form-control' placeholder='Ingrese localidad' ")?>
                </div>
                <div class="form-group">
                  <label>Provincia</label>
                  <?php echo Form::dbSelect("a.provincia_id",NULL,array("provincia","combo"),NULL,"class='form-control' ")?>
                </div>
                <!-- /.form group -->

              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                  <button type="submit" class="btn btn-info float-right">Registrar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
      
      