  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-success">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
                <a href="<?php echo $linkVolver;?>" class="btn btn-primary float-right">Volver</a>
              </div>
              <div class="card-body">
                <?php echo Form::hidden("a.id")?>
                <div class="form-group">
                  <label>Rol</label>
                  <?php echo Form::dbSelect("a.rol_id",NULL,array("rol","combo"),NULL,"disabled class='form-control'")?>
                </div>
                <div class="form-group">
                  <label>Módulo</label>
                  <?php echo Form::dbSelect("a.modulo_id",NULL,array("modulo","combo"),NULL,"disabled class='form-control'")?>
                </div>
                <div class="form-group">
                  <label>Controlador</label>
                  <?php echo Form::text("a.controlador","disabled maxlength='30' class='form-control' placeholder='Ingrese el nombre del Controlador'")?>
                </div>
                <!-- /.form group -->

                <!-- time Picker -->
              </div>
              <?php Flash::valid("¿Desea Activar este Controlador? Por favor, confirme...");?>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success float-right">Si, Activar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
