  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-info">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
                <a href="<?php echo $linkVolver;?>" class="btn btn-primary float-right">Volver</a>
              </div>
              <div class="card-body">
                
                <div class="form-group">
                  <label>Negocio/Institución</label>
                  <?php echo Form::dbSelect("a.negocio_id",NULL,array("negocio","combo"),NULL,"class='form-control'")?>
                </div>
                <div class="form-group">
                  <label>Módulo</label>
                  <?php echo Form::dbSelect("a.modulo_id",NULL,array("modulo","combo"),NULL,"class='form-control'")?>
                </div>
                <div class="form-group">
                  <label>Precio Mensual</label>
                  <?php echo Form::text("a.precio","maxlength='10' class='form-control' placeholder='Precio x Mes'")?>
                </div>
                <!-- /.form group -->

                <!-- time Picker -->
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                  <button type="submit" class="btn btn-info float-right">Registrar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
          <div class="col-md-6">
          <div class="row">
              <table class="table table-striped" id="example1">
                  <thead >
                      <tr>
                          <td>Contrataciones Activas</td>
                      </tr>
                  </thead>
                  <tbody>
                      <?php foreach ($lista as $value) { ?>
                      <tr>
                          <td><i class="fa fa-home text-info"></i> <?php echo $value->neg_nom;?><br>
                              
                              <i class="fas fa-book text-info"></i> <?php echo $value->modulo?><br>
                              <i class="fas fa-edit text-info"></i> <?php echo $value->precio?><br>
                              <i class="fas fa-calendar text-success"></i> <?php echo Fecha::yymmddhmsToddmmyyhms($value->desde)?><br>
                              <i class="fas fa-calendar text-danger"></i> <?php echo Fecha::yymmddhmsToddmmyyhms($value->hasta)?>
                          </td>
                      </tr>
                      <?php }?>
                      
                      
                      <?php ?>
                      
                  </tbody>
              </table>
              
          </div>
          </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
<script>
    $(document).ready(function (){
        $("#a_negocio_id").change(function (){
            window.location="<?php echo PUBLIC_PATH."../../"?>contrata/add/"+$("#a_negocio_id").val();
        });
    });
//    $(function () {
//        $("#example1").DataTable({
//            "responsive": true,
//            "autoWidth": false,
//        });
//        
//    });
</script>