<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>KumbiaPHP Framework</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<?php echo PUBLIC_PATH?>img/lista.svg" type="image/x-icon">
    <link rel="shortcut icon" href="<?php echo PUBLIC_PATH?>img/lista.svg" type="image/x-icon">
    <link rel="apple-touch-icon" href="<?php echo PUBLIC_PATH?>img/lista.svg">
  
<!--<link href="<?php echo PUBLIC_PATH?>bootstrap450/dist/css/bootstrap.css" rel="stylesheet">
<script src="<?php echo PUBLIC_PATH?>bootstrap450/dist/vendor/jquery.slim.min.js"></script>
<script src="<?php echo PUBLIC_PATH?>bootstrap450/dist/js/bootstrap.min.js"></script>-->
<!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="<?php echo PUBLIC_PATH?>assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="<?php echo PUBLIC_PATH?>assets/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="<?php echo PUBLIC_PATH?>assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="<?php echo PUBLIC_PATH?>assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="<?php echo PUBLIC_PATH?>assets/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="<?php echo PUBLIC_PATH?>assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="<?php echo PUBLIC_PATH?>assets/vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="<?php echo PUBLIC_PATH?>assets/css/style.css" rel="stylesheet">
 </head>
 
<body>
  <?php View::partial('kumbia/menu_out') ?>

  <?php View::content() ?>
    
  <!-- Vendor JS Files -->
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/jquery/jquery.min.js"></script>
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/php-email-form/validate.js"></script>
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/venobox/venobox.min.js"></script>
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="<?php echo PUBLIC_PATH?>assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
    
</body>
</html>
