  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-success">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
                <a href="<?php echo $linkVolver;?>" class="btn btn-primary float-right">Volver</a>
              </div>
              <div class="card-body">
                  <?php echo Form::hidden("a.id")?>
                <div class="form-group">
                  <label>Nombre del Negocio</label>
                  <?php echo Form::text("a.neg_nom","disabled maxlength='45' class='form-control' placeholder='Ingrese el Nombre del Negocio'")?>
                </div>
<!--                <div class="form-group">
                  <label>CUIT del Negocio</label>
                  <?php echo Form::text("a.neg_cuit","disabled maxlength='15' class='form-control' placeholder='Ingrese el CUIT'")?>
                </div>-->
<!--                <div class="form-group">
                  <label>Teléfono/s</label>
                  <?php echo Form::text("a.neg_tel","disabled maxlength='30' class='form-control' placeholder='Ingrese el/los Teléfono/s'")?>
                </div>-->
<!--                <div class="form-group">
                  <label>Email</label>
                  <?php echo Form::text("a.neg_mail","disabled maxlength='30' class='form-control' placeholder='Correo Electrónico'")?>
                </div>-->
                <div class="form-group">
                  <label>Domicilio</label>
                  <?php echo Form::text("a.neg_dom","disabled maxlength='45' class='form-control' placeholder='Dirección Completa del Negocio'")?>
                </div>
                <div class="form-group">
                  <label>Rubro</label>
                  <?php echo Form::dbSelect("a.rubro_id",NULL,array("rubro","combo"),NULL,"disabled class='form-control'")?>
                </div>
                <div class="form-group">
                  <label>Provincia</label>
                  <?php echo Form::dbSelect("a.provincia_id",NULL,array("provincia","combo"),NULL,"disabled class='form-control'")?>
                </div>
                <div class="form-group">
                  <label>Localidad</label>
                  <?php echo Form::select("a.localidad_id",array(),"disabled class='form-control'")?>
                </div>
                  <h3>Administración</h3>
                <div class="form-group">
                  <label>Nombre del Administrador</label>
                  <?php echo Form::text("a.adm_nom","disabled maxlength='45' class='form-control' placeholder='Apellido y Nombre'")?>
                </div>
                <div class="form-group">
                  <label>Celular</label>
                  <?php echo Form::text("a.adm_cel","disabled disabled maxlength='15' class='form-control' placeholder='Celular del Administrador'")?>
                </div>
                <div class="form-group">
                  <label>Usuario</label>
                  <?php echo Form::text("a.usu","disabled maxlength='40' class='form-control' placeholder='Nombre de Usuario para el ingreso'")?>
                </div>
                  
                <!-- time Picker -->
              </div>
              <?php echo Flash::error("¿Desea Activar este Negocio? Por favor, Confirme")?>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success float-right">Si, Activar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <script>
  $(document).ready(function (){
      verLocalidades();
      $("#a_provincia_id").change(function (){
          verLocalidades()
      });
  });
      

function verLocalidades()
{
    var prov_id = $("#a_provincia_id").val();
    var loc_id =  $("#a_localidad_id").val();
    var datos={"prov_id": prov_id, "loc_id": loc_id};
    var url="<?php echo PUBLIC_PATH."../../localidad/lista_por_provincia"?>";
    $.post(url, datos, function (e){
//        console.log(e);
       $("#a_localidad_id").html(e) ;        
    });
    
    
}
      
  </script>
  
  