  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-info">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
                <!--<a href="<?php //echo $linkVolver;?>" class="btn btn-primary float-right">Volver</a>-->
              </div>
              <div class="card-body">
                <div class="form-group">
                  <label>Domicilio del Negocio</label>
                  <?php echo Form::text("a.neg_dom","maxlength='45' class='form-control' placeholder='Ingrese el Nombre del Negocio'")?>
                </div>
                <div class="form-group">
                  <label>Provincia</label>
                  <?php echo Form::dbSelect("a.provincia_id",NULL,array("provincia","combo"),NULL,"class='form-control'")?>
                </div>
                <div class="form-group">
                  <label>Localidad</label>
                  <?php echo Form::select("a.localidad_id",array(),"class='form-control'")?>
                </div>
                  
                <!-- time Picker -->
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                  <button type="submit" class="btn btn-info float-right">Actualizar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <script>
  $(document).ready(function (){
      verLocalidades();
      $("#a_provincia_id").change(function (){
          verLocalidades()
      });
  });
      

function verLocalidades()
{
    var prov_id = $("#a_provincia_id").val();
    var loc_id = "<?php echo  $a->localidad_id;?>";
    var datos={"prov_id": prov_id, "loc_id": loc_id};
    var url="<?php echo PUBLIC_PATH."../../localidad/lista_por_provincia"?>";
//    console.log(loc_id);
    $.post(url, datos, function (e){
        console.log(e);
       $("#a_localidad_id").html(e) ;        
    });
    
    
}
      
  </script>
  
  