  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-success">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
                <a href="<?php echo $linkVolver;?>" class="btn btn-primary float-right">Volver</a>
              </div>
              <div class="card-body">
                <?php echo Form::hidden("a.id")?>
                <div class="form-group">
                  <label>Artículo</label>
                  <?php echo Form::text("a.art_nom","disabled maxlength='60' class='form-control' placeholder='Ingrese Nombre del Artículo'")?>
                </div>
                <div class="form-group">
                  <label>Precio</label>
                  <?php echo Form::text("a.art_pre","disabled maxlength='8' class='form-control' placeholder='Precio de venta del Artículo'")?>
                </div>
                <div class="form-group">
                  <label>Marca</label>
                  <?php echo Form::dbSelect("a.marca_id",NULL,array("marca","combo"),NULL,"disabled class='form-control' ")?>
                </div>
                <div class="form-group">
                  <label>Unidad</label>
                  <?php echo Form::dbSelect("a.unidad_id",NULL,array("unidad","combo"),NULL,"disabled class='form-control' ")?>
                </div>
                <div class="form-group">
                  <label>Categoría</label>
                  <?php echo Form::dbSelect("a.categoria_id",NULL,array("categoria","combo"),NULL,"disabled class='form-control' ")?>
                </div>
                <div class="form-group">
                  <label>Publicacido</label>
                  <?php echo Form::select("a.publicado", Articulo::$PUBLICADO,"disabled class='form-control' ")?>
                </div>
                <!-- /.form group -->

                <!-- time Picker -->
              </div>
              <!-- /.card-body -->
              <?php Flash::valid("¿Realmente Desea Activar Este Registro? Por favor, Confirme")?>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success float-right">Si, Activar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
