  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <div class="row">
          <div class="col-md-6">
            <!-- /.card -->
            <?php View::content();?>
                <form method="POST">
            <div class="card card-danger">
              <div class="card-header">
                  
                <h3 class="card-title"><?php echo $sub;?></h3>
                <a href="<?php echo $linkVolver;?>" class="btn btn-primary float-right">Volver</a>
              </div>
              <div class="card-body">
                  <?php echo Form::hidden("a.id")?>
                  <h5>Datos Para Ingreso</h5>
                <div class="form-group">
                  <label>Usuario</label>
                  <?php echo Form::text("a.usu","disabled maxlength='40' class='form-control' required placeholder='Ingrese Usuario'")?>
                </div>
                  <h5>Datos Del Negocio</h5>
                <div class="form-group">
                  <label>Negocio</label>
                  <?php echo Form::text("a.cli_neg","disabled maxlength='45' class='form-control' required placeholder='Ingrese Nombre del Negocio'")?>
                </div>
                <div class="form-group">
                  <label>Domicilio</label>
                  <?php echo Form::text("a.cli_dom","disabled maxlength='45' class='form-control' required placeholder='Ingrese Domicilio del Negocio'")?>
                </div>
                <div class="form-group">
                  <label>Provincia</label>
                  <?php echo Form::dbSelect("a.provincia_id",NULL,array("provincia","combo"),NULL,"disabled class='form-control' ")?>
                </div>
                <div class="form-group">
                  <label>Localidad</label>
                  <?php echo Form::select("a.localidad_id",array(),"disabled class='form-control' ")?>
                </div>
                  
                  <h5>Datos Del Cliente</h5>
                <div class="form-group">
                  <label>Apellido y Nombre</label>
                  <?php echo Form::text("a.cli_nom","disabled maxlength='45' class='form-control' required placeholder='Nombre Completo del Cliente'")?>
                </div>
                <div class="form-group">
                  <label>DNI</label>
                  <?php echo Form::text("a.cli_dni","disabled maxlength='8' class='form-control' required placeholder='DNI del Cliente'")?>
                </div>
                <div class="form-group">
                  <label>Celular</label>
                  <?php echo Form::text("a.cli_cel","disabled maxlength='15' class='form-control' required placeholder='Celular del Cliente'")?>
                </div>
                <!-- /.form group -->

                <!-- time Picker -->
              </div>
              <?php Flash::error("¿Realmente Desea Desactivar este Registro? Por favor, Confirme ...")?>
              <div class="card-footer">
                  <button type="submit" class="btn btn-danger float-right">Si, Desactivar</button>
              </div>
            </div>
            </form>
            <!-- /.card -->

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <script>
  $(document).ready(function (){
      verLocalidades();
      $("#a_provincia_id").change(function (){
          verLocalidades()
      });
  });
      

function verLocalidades()
{
    var prov_id = $("#a_provincia_id").val();
    var loc_id =  "<?php echo $a->localidad_id?>";
    var datos={"prov_id": prov_id, "loc_id": loc_id};
    var url="<?php echo PUBLIC_PATH."../../localidad/lista_por_provincia"?>";
    $.post(url, datos, function (e){
//        console.log(e);
       $("#a_localidad_id").html(e) ;        
    });
    
    
}
      
  </script>

  