  
<style>
.dropdown-toggle::after {
    display: none;
}    
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-10">
                    <!-- /.card -->
                    <div class="card card-info">
                        <div class="card-header">

                            <h3 class="card-title"><?php echo $sub; ?></h3>
                            <!--<a href="<?php //echo $linkAdd; ?>" class="btn btn-primary float-right">Agregar</a>-->
                        </div>
                        <div class="card-body">



<div class="row">
        <?php foreach($lista as $r){?>
          <div class="col-12 col-sm-6 col-md-4">
              <a href="<?php echo $linkEmpresas.$r->id;?>">
                <div class="info-box">
                  <span class="info-box-icon bg-info elevation-1">

                      <img src="<?php echo $r->iconox?>">
                  </span>

                  <div class="info-box-content">
                    <span class="info-box-text"><?php echo $r->rubro?></span>
                    <span class="info-box-number">
                      <?php echo $r->cant?>
                      <small>negocios</small>
                    </span>
                  </div>
                  <!-- /.info-box-content -->
                </div>
             </a>
            <!-- /.info-box -->
          </div>
        <?php }?>
    
          <!-- /.col -->
<!--          <div class="col-12 col-sm-6 col-md-4">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-thumbs-up"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Likes</span>
                <span class="info-box-number">41,410</span>
              </div>
            </div>

          </div>-->

          
          
<!--          <div class="clearfix hidden-md-up"></div>
          <div class="col-12 col-sm-6 col-md-4">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Sales</span>
                <span class="info-box-number">760</span>
              </div>
            </div>
          </div>-->
<!--          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-users"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">New Members</span>
                <span class="info-box-number">2,000</span>
              </div>
            </div>

          </div>-->
        </div>                            
                            
                            
                            <!-- time Picker -->
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script>
    
//    $(function () {
//        $("#example1").DataTable({
//            "responsive": true,
//            "autoWidth": false,
//        });
//        
//    });
</script>